dependencies/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('maqe', 'PostController@index');

Route::prefix('MRTA-backend/console')->group(function (){
    Auth::routes();


    Route::get('email', function (){
        return view('email');
    });

    //Dashboard
    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    //News
    Route::prefix('news')->group(function (){
        Route::resource('news-categories', 'NewsCategoryController');
        Route::post('news-categories/destroymany', 'NewsCategoryController@destroyMany')->name('news_category_destroymany');
    });
    Route::resource('news', 'NewsController');
    Route::post('news/destroymany', 'NewsController@destroyMany')->name('news_destroymany');
    Route::get('news/category-set', 'NewsController@setCategory')->name('news_typeset');

    //Pages
    Route::resource('pages', 'PagesController');
    Route::post('pages/destroymany', 'PagesController@destroyMany')->name('pages_destroymany');

    //Menus
    Route::resource('menus', 'MenusController');

    //Media
    Route::put('media/uploads', 'MediaController@upload')->name('media_upload');
    Route::resource('media', 'MediaController');

    //Construct
    Route::get('construct/update/status/{id}', 'ConstructController@update_status')->name('construct_update_status');
    Route::resource('stations', 'StationController');
    //Stations
    Route::post('stations/destroymany', 'StationController@destroyMany')->name('stations_destroymany');
    Route::prefix('stations')->group(function (){

        //Folder
        Route::post('folder/{id}', 'StationFolderController@store')->name('add_folder');
        Route::get('folder/{id}', 'StationFolderController@show')->name('show_folder');
        Route::put('folder/{id}', 'StationFolderController@update')->name('update_folder');
        Route::delete('folder/{id}', 'StationFolderController@destroy')->name('delete_folder');

        //Uploads
        Route::put('uploads/{id}', 'StationImageController@upload')->name('uploads_progress');

        //Uploads
        Route::delete('uploads/{id}', 'StaionImageController@destroy')->name('uploads_delete');

        //Percent Update
        Route::resource('percent', 'ConstructPercentController');

    });

    Route::prefix('construct')->group(function (){

        //Folder
        Route::resource('pictures', 'ConstructPictureController');

        //Uploads
        Route::put('uploads/{id}', 'ConstructImageController@upload')->name('uploads_progress');

        //Uploads
        Route::delete('uploads/{id}', 'ConstructImageController@destroy')->name('uploads_delete');

        //Percent Update
        Route::resource('percent', 'ConstructPercentController');

    });

    //Construct
    Route::resource('construct', 'ConstructController');
    Route::post('construct/destroymany', 'ConstructController@destroyMany')->name('construct_destroymany');

    //Settings
    Route::prefix('settings')->group(function (){
        //Users
        Route::resource('users', 'UserController');
        Route::post('users/destroymany', 'UserController@destroyMany')->name('users_destroymany');


        //Roles
        Route::resource('roles', 'RoleController');
        Route::post('roles/destroymany', 'RoleController@destroyMany')->name('roles_destroymany');


        //Generals
        Route::resource('generals', 'GeneralController');

        //Email
        Route::resource('email', 'EmailController');

        //Permission
        Route::resource('permissions', 'PermissionController');
        Route::post('permissions/destroymany', 'PermissionController@destroyMany')->name('permission_destroymany');

        //Default Status
        Route::resource('statuses', 'StatusController');

        //Languages
        Route::resource('languages', 'LanguageController');
        Route::post('languages/destroymany', 'LanguageController@destroyMany')->name('language_destroymany');
        Route::get('languages/makedefault/{id}', 'LanguageController@makeDefault')->name('languages_makedefault');

    });


});

dependencies/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

dependencies/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;
use Auth;

//Importing laravel-permission models
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

//Enables us to output flash messaging
use Session;

class UserController extends Controller {

    public function __construct() {
        $this->middleware(['auth', 'manageSetting']); //isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        //Get all users and pass it to the view
        $users = User::orderBy('id','desc')->paginate(10);
        return view('users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //Get all roles and pass it to the view
        $roles = Role::get();
        return view('users.create', ['roles'=>$roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //Validate name, email and password fields
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users',
            'password'=>'required|min:6|confirmed',
            'roles'=>'required'
        ],[
            'name.required' => 'จำเป็นต้องระบุชื่อ',
            'name.max:120' => 'ชื่อต้องไม่เกิน 120 ตัวอักษร',
            'email.required'=>'จำเป็นต้องระบุอีเมล',
            'email.email'=>'ระบุอีเมลในรูปแบบ someone@example.com',
            'email.unique:users'=>'อีเมลที่ระบุถูกใช้งานแล้ว',
            'password.required'=>'จำเป็นต้องระบุรหัสผ่าน',
            'password.min:6'=>'ระบุรหัสผ่านอย่างน้อย 6 ตัว',
            'password.confirmed'=>'กรุณายืนยันรหัสผ่าน',
            'roles.required' => 'จำเป็นต้องกำหนดสิทธิ์การเข้าถึง'
        ]);

        $user = User::create($request->only('email', 'name', 'password')); //Retrieving only the email and password data

        $roles = $request['roles']; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles)) {

            foreach ($roles as $role) {
                $role_r = Role::where('id', '=', $role)->firstOrFail();
                $user->assignRole($role_r); //Assigning role to user
            }
        }
        //Redirect to the users.index view and display message
        return redirect()->route('users.index')
            ->with('flash_message',
                'สร้างบัญชีผู้ใช้เรียบร้อยแล้ว');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect()->route('users.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $user = User::findOrFail($id); //Get user with specified id
        $roles = Role::get(); //Get all roles

        return view('users.edit', compact('user', 'roles')); //pass user and roles data to view

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $user = User::findOrFail($id); //Get role specified by id

        //Validate name, email and password fields
        $this->validate($request, [
            'name'=>'required|max:120',
            'email'=>'required|email|unique:users,email,'.$id,
            'roles'=>'required'
        ],[
            'name.required' => 'จำเป็นต้องระบุชื่อ',
            'name.max:120' => 'ชื่อต้องไม่เกิน 120 ตัวอักษร',
            'email.required'=>'จำเป็นต้องระบุอีเมล',
            'email.email'=>'ระบุอีเมลในรูปแบบ someone@example.com',
            'email.unique:users,email,'.$id=>'อีเมลที่ระบุถูกใช้งานแล้ว',
            'roles.required' => 'จำเป็นต้องกำหนดสิทธิ์การเข้าถึง'
        ]);
        $input = $request->only(['name', 'email']); //Retreive the name, email and password fields
        $roles = $request->roles; //Retreive all roles
        $user->fill($input)->save();

        if (isset($roles)) {
            $user->roles()->sync($roles);  //If one or more role is selected associate user to roles
        }
        else {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }
        return redirect()->route('users.edit',$id)
            ->with('flash_message',
                'บันทึกข้อมูลเรียบร้อยแล้ว');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //Find a user with a given id and delete
        $user = User::findOrFail($id);

        if ($user->email == Auth::user()->email) {
            return redirect()->route('users.index')
                ->with('danger',
                    'ไม่สามารถลบบัญชีผู้ใช้นี้ได้ เนื่องจากคุณกำลังเข้าสู่ระบบด้วยบัญชีผู้ใช้นี้');
        }
        else{
            $user->delete();
            return redirect()->route('users.index')
                ->with('flash_message',
                    'ลบบัญชีผู้ใช้เรียบร้อยแล้ว');
        }



    }

    public function destroyMany(Request $request)
    {
        if ($request->multi_id != null){
            $users = User::findOrFail($request->multi_id);

            //Make it impossible to delete this specific permission
            $msg = "";
            $count_error=0;
            $count_delete=0;
            foreach ($users as $user){
                if ($user->email == Auth::user()->email) {
                    $msg .= $user->email;
                    $count_error++;

                }
                else{
                    $user->delete();
                    $count_delete++;
                }

            }
            if($count_error != 0 && $count_delete != 0){
                return redirect()->route('users.index')
                    ->with(['flash_message'=>
                        'Users deleted.','danger'=>'ไม่สามารถลบบัญชี '.$msg." เนื่องจากคุณกำลังเข้าสู่ระบบด้วยบัญชีผู้ใช้นี้"]);
            }
            else if($count_error == 0 && $count_delete != 0){
                return redirect()->route('users.index')
                    ->with(['flash_message'=>
                        'ลบบัญชีผู้ใช้เรียบร้อยแล้ว']);
            }
            else if($count_error != 0 && $count_delete == 0){
                return redirect()->route('users.index')
                    ->with(['danger'=>'ไม่สามารถลบบัญชี '.$msg." เนื่องจากคุณกำลังเข้าสู่ระบบด้วยบัญชีผู้ใช้นี้"]);
            }

        }
        else{
            return redirect()->route('users.index')
                ->with('warning',
                    'กรุณาเลือกบัญชีผู้ใช้อย่างน้อย 1 บัญชี');

        }
    }
}

dependencies/resources/views/users/create.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-orange">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li class="active">
                        <a href="{{route('users.index')}}">จัดการบัญชีผู้ใช้</a>
                    </li>

                    <li>
                        <a href="{{route('roles.index')}}"><span class="title">สิทธิ์การเข้าถึง</span></a>
                    </li>

                    <li>
                        <a href="{{route('generals.index')}}"><span class="title">ข้อมูลทั่วไป</span></a>
                    </li>

                    <li>
                        <a href="{{route('email.index')}}"><span class="title">อีเมลระบบ</span></a>
                    </li>

                    <li>
                        <a href="{{route('statuses.index')}}"><span class="title">สถานะเริ่มต้น</span></a>
                    </li>


                    <li>
                        <a href="{{route('languages.index')}}"><span class="title">ภาษา</span></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-orange">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">หน้าแรก</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">ตั้งค่า</a></li>
                <li class="breadcrumb-item"><a href="{{route('users.index')}}">จัดการบัญชีผู้ใช้</a></li>
                <li class="breadcrumb-item active">เพิ่มบัญชีผู้ใช้</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>เพิ่มบัญชีผู้ใช้

                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="card card-transparent">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-12">
                        @if(Session::has('flash_message'))
                            <div class="alert alert-success" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                {!! Session('flash_message') !!}
                            </div>

                        @endif
                        @if (sizeof($errors) != 0)
                            <div class="alert alert-danger" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                @if($errors->has('name')) {{$errors->first('name')}}<br>@endif
                                @if($errors->has('email')) {{$errors->first('email')}}<br>@endif
                                @if($errors->has('password')) {{$errors->first('password')}}<br>@endif
                                @if($errors->has('roles')) {{$errors->first('roles')}}<br>@endif

                            </div>

                        @endif
                        <p class="small hint-text">* จำเป็นต้องระบุ</p>
                        <form id="form-work" class="form-horizontal" role="form" autocomplete="off" action="{{route('users.store')}}" method="post" novalidate="novalidate">
                            {{csrf_field()}}
                            <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">ชื่อ *</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control error" id="name" placeholder="สมชาย รักโลก" name="name"  value="{{old('name')}}" required="" aria-required="true" aria-invalid="true">
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('email') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">อีเมล *</label>
                                <div class="col-md-9">
                                    <input type="email" class="form-control error" id="email" placeholder="someone@example.com" name="email"  value="{{old('email')}}" required="" aria-required="true" aria-invalid="true">
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('password') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">รหัสผ่าน *</label>
                                <div class="col-md-9">
                                    <input type="password" class="form-control error" id="password" name="password"  value="{{old('password')}}" required="" aria-required="true" aria-invalid="true">
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">ยืนยันรหัสผ่าน *</label>
                                <div class="col-md-9">
                                    <input type="password" class="form-control error" id="password_confirmation" name="password_confirmation"  value="" required="" aria-required="true" aria-invalid="true">
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('roles') ? ' has-error' : '' }}">
                                @if(!$roles->isEmpty())

                                    <label class="col-md-3 control-label">สิทธิ์การเข้าถึง *</label>
                                    <div class="col-md-9">
                                        @foreach ($roles as $role)
                                            {{ Form::radio('roles',  $role->id ) }}
                                            {{ Form::label($role->name, ucfirst($role->name)) }}<br>
                                        @endforeach
                                    </div>
                                @endif
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-3">
                                </div>
                                <div class="col-md-9">
                                    <a href="{{route('users.index')}}" class="btn btn-hotel btn-primary-hotel">กลับ</a>
                                    <button class="btn btn-hotel btn-sec-hotel" type="submit">เพิ่ม</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>



        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
@endsection

dependencies/resources/views/users/index.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-orange">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li class="active">
                        <a href="javascript:;">จัดการบัญชีผู้ใช้</a>
                    </li>

                    <li>
                        <a href="{{route('roles.index')}}"><span class="title">สิทธิ์การเข้าถึง</span></a>
                    </li>
                    <li>
                        <a href="{{route('generals.index')}}"><span class="title">ข้อมูลทั่วไป</span></a>
                    </li>

                    <li>
                        <a href="{{route('email.index')}}"><span class="title">อีเมลระบบ</span></a>
                    </li>

                    <li>
                        <a href="{{route('statuses.index')}}"><span class="title">สถานะเริ่มต้น</span></a>
                    </li>

                    <li>
                        <a href="{{route('languages.index')}}"><span class="title">ภาษา</span></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-orange">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">หน้าแรก</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">ตั้งค่า</a></li>
                <li class="breadcrumb-item active">จัดการผู้ใช้ระบบ</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>จัดการผู้ใช้ระบบ

                    <a href="{{ route('users.create') }}" class="btn btn-hotel btn-primary-hotel btn-top-page pull-right"><i class="icon-plus"></i> เพิ่มบัญชีผู้ใช้</a>
                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <!-- START card -->
        <div class="card card-transparent">
            <div class="card-block">
                @if(Session::has('flash_message'))
                    <div class="alert alert-success" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('flash_message') !!}
                    </div>

                @endif
                @if(Session::has('warning'))
                    <div class="alert alert-warning" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('warning') !!}
                    </div>

                @endif
                @if(Session::has('danger'))
                    <div class="alert alert-danger" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('danger') !!}
                    </div>

                @endif
                <div class="table-responsive">
                    <div id="basicTable_wrapper" class="dataTables_wrapper no-footer">
                        <form action="{{route('users_destroymany')}}" method="post">
                            {{csrf_field()}}
                            <table class="table table-hover dataTable no-footer" id="basicTable" role="grid">
                                <thead>
                                <tr role="row">
                                    <th style="width: 1%" class="sorting_desc" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="No.: activate to sort column ascending" aria-sort="descending">ลำดับ</th>
                                    <th style="width: 41.5%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="Title: activate to sort column ascending">ชื่อ</th>
                                    <th style="width: 41.5%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="Title: activate to sort column ascending">อีเมล</th>
                                    <th style="width: 15%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1">จัดการ</th>
                                    <th style="width:1%" class="text-center sorting_disabled" rowspan="1" colspan="1" aria-label="">
                                        <button class="btn btn-link"><i class="icon-trash"></i>
                                        </button>
                                    </th>
                                </tr>

                                </thead>
                                <tbody>
                                @if(sizeof($users) != 0)
                                    @foreach ($users as $user)
                                        <tr role="row" class="odd">
                                            <td class="v-align-middle sorting_1">
                                                {{ $user->id }}
                                            </td>
                                            <td class="v-align-middle">
                                                {{ $user->name }}
                                            </td>
                                            <td class="v-align-middle">
                                                {{ $user->email }}
                                            </td>
                                            <td class="v-align-middle">
                                                <a href="{{ route('users.edit', $user->id) }}" class="btn btn-hotel btn-edit pull-left" style="margin-right: 3px;"><i class="icon-pencil"></i></a>
                                                <button type="button" class="btn btn-hotel btn-delete pull-left" style="margin-right: 3px;" data-target="#deleteModal{{$user->id}}" data-toggle="modal"><i class="icon-trash"></i></button>

                                            </td>
                                            <td class="v-align-middle">
                                                <div class="checkbox text-center">
                                                    <input type="checkbox" value="{{$user->id}}" id="checkbox{{$user->id}}" name="multi_id[]">
                                                    <label for="checkbox{{$user->id}}" class="no-padding no-margin"></label>
                                                </div>
                                            </td>
                                        </tr>

                                    @endforeach
                                    @else
                                    <tr><td></td><td>ไม่พบบัญชีผู้ใช้ในตอนนี้.</td><td></td><td></td><td></td></tr>

                                @endif








                                </tbody>
                                <tfoot>
                                <tr><td></td><td></td><td></td><td style="text-align: right">เลือก:</td><td><button type="button" class="btn btn-xs btn-hotel btn-delete" data-target="#deleteMany" data-toggle="modal"><i class="icon-trash"></i> ลบ</button></td>
                                    <div class="modal fade fill-in disable-scroll" id="deleteMany" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header clearfix text-left">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-center m-t-20">
                                                    <h5>คุณต้องการลบบัญชีผู้ใช้ที่เลือกใช่หรือไม่ ?</h5>
                                                    <button type="button" class="btn btn-hotel btn-primary-hotel" data-dismiss="modal" aria-hidden="true">ยกเลิก</button>&nbsp;
                                                    <button class="btn btn-hotel btn-delete" type="submit">ลบ</button>

                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                    </div>
                                </tr>



                                </tfoot>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div style="text-align: center">
                {{$users->links()}}
            </div>
        </div>
        <!-- END card -->
        <!-- DELETE MODAL -->
        @if(sizeof($users) != 0)
            @foreach ($users as $user)
               <div class="modal fade fill-in disable-scroll" id="deleteModal{{$user->id}}" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header clearfix text-left">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                                        </button>
                                    </div>
                                    <div class="modal-body text-center m-t-20">
                                        <form action="{{ route('users.destroy', $user->id) }}" method="post">
                                            <input type="hidden" name="_method" value="delete" />
                                            {!! csrf_field() !!}

                                            <h5>คุณต้องการลบบัญชี {{$user->name}} ใช่หรือไม่ ?</h5>
                                            <button type="button" class="btn btn-hotel btn-primary-hotel" data-dismiss="modal" aria-hidden="true">ยกเลิก</button>&nbsp;
                                            <button class="btn btn-hotel btn-delete" type="submit">ลบ</button>
                                        </form>
                                    </div>
                                </div>
                                <!-- /.modal-content -->
                            </div>
                            <!-- /.modal-dialog -->
                        </div>


        @endforeach
    @endif


        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->

@endsection