dependencies/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('maqe', 'PostController@index');

Route::prefix('MRTA-backend/console')->group(function (){
    Auth::routes();


    Route::get('email', function (){
        return view('email');
    });

    //Dashboard
    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    //News
    Route::prefix('news')->group(function (){
        Route::resource('news-categories', 'NewsCategoryController');
        Route::post('news-categories/destroymany', 'NewsCategoryController@destroyMany')->name('news_category_destroymany');
    });
    Route::resource('news', 'NewsController');
    Route::post('news/destroymany', 'NewsController@destroyMany')->name('news_destroymany');
    Route::get('news/category-set', 'NewsController@setCategory')->name('news_typeset');

    //Pages
    Route::resource('pages', 'PagesController');
    Route::post('pages/destroymany', 'PagesController@destroyMany')->name('pages_destroymany');

    //Menus
    Route::resource('menus', 'MenusController');

    //Media
    Route::put('media/uploads', 'MediaController@upload')->name('media_upload');
    Route::resource('media', 'MediaController');

    //Construct
    Route::get('construct/update/status/{id}', 'ConstructController@update_status')->name('construct_update_status');
    Route::resource('stations', 'StationController');
    //Stations
    Route::post('stations/destroymany', 'StationController@destroyMany')->name('stations_destroymany');
    Route::prefix('stations')->group(function (){

        //Folder
        Route::post('folder/{id}', 'StationFolderController@store')->name('add_folder');
        Route::get('folder/{id}', 'StationFolderController@show')->name('show_folder');
        Route::put('folder/{id}', 'StationFolderController@update')->name('update_folder');
        Route::delete('folder/{id}', 'StationFolderController@destroy')->name('delete_folder');

        //Uploads
        Route::put('uploads/{id}', 'StationImageController@upload')->name('uploads_progress');

        //Uploads
        Route::delete('uploads/{id}', 'StaionImageController@destroy')->name('uploads_delete');

        //Percent Update
        Route::resource('percent', 'ConstructPercentController');

    });

    Route::prefix('construct')->group(function (){

        //Folder
        Route::resource('pictures', 'ConstructPictureController');

        //Uploads
        Route::put('uploads/{id}', 'ConstructImageController@upload')->name('uploads_progress');

        //Uploads
        Route::delete('uploads/{id}', 'ConstructImageController@destroy')->name('uploads_delete');

        //Percent Update
        Route::resource('percent', 'ConstructPercentController');

    });

    //Construct
    Route::resource('construct', 'ConstructController');
    Route::post('construct/destroymany', 'ConstructController@destroyMany')->name('construct_destroymany');

    //Settings
    Route::prefix('settings')->group(function (){
        //Users
        Route::resource('users', 'UserController');
        Route::post('users/destroymany', 'UserController@destroyMany')->name('users_destroymany');


        //Roles
        Route::resource('roles', 'RoleController');
        Route::post('roles/destroymany', 'RoleController@destroyMany')->name('roles_destroymany');


        //Generals
        Route::resource('generals', 'GeneralController');

        //Email
        Route::resource('email', 'EmailController');

        //Permission
        Route::resource('permissions', 'PermissionController');
        Route::post('permissions/destroymany', 'PermissionController@destroyMany')->name('permission_destroymany');

        //Default Status
        Route::resource('statuses', 'StatusController');

        //Languages
        Route::resource('languages', 'LanguageController');
        Route::post('languages/destroymany', 'LanguageController@destroyMany')->name('language_destroymany');
        Route::get('languages/makedefault/{id}', 'LanguageController@makeDefault')->name('languages_makedefault');

    });


});

dependencies/app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
//Importing laravel-permission models
use Illuminate\Support\Facades\Redirect;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

use Session;
use Validator;

class RoleController extends Controller {

    public function __construct() {
        $this->middleware(['auth','manageSetting']);//isAdmin middleware lets only users with a //specific permission permission to access these resources
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $roles = Role::orderBy('id', 'desc')->paginate(10);//Get all roles

        return view('roles.index')->with('roles', $roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $permissions = Permission::all();//Get all permissions

        return view('roles.create', ['permissions'=>$permissions]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        //Validate name and permissions field
        $validation = Validator::make( $request->all(), [
                'name'=>'required|unique:roles',
                'permissions' =>'required',
            ],
        [
            'name.required' => 'จำเป็นต้องระบุชื่อ',
            'name.unique:roles' => 'ชื่อที่ระบุถูกใช้งานแล้ว',
            'permissions.required' => 'จำเป็นต้องกำหนดสิทธิ์การเข้าถึง'
        ]
        );
        if ( $validation->fails() ) {
            // change below as required
            return \Redirect::back()->withInput()->withErrors( $validation->messages() );
        }
        else {
            $name = $request['name'];
            $role = new Role();
            $role->name = $name;

            $permissions = $request['permissions'];

            $role->save();
            //Looping thru selected permissions
            foreach ($permissions as $permission) {
                $p = Permission::where('id', '=', $permission)->firstOrFail();
                //Fetch the newly created role and assign permission
                $role = Role::where('name', '=', $name)->first();
                $role->givePermissionTo($p);
            }

            return redirect()->route('roles.index')
                ->with('flash_message',
                    'เพิ่มสิทธิ์ '. $role->name.' เรียบร้อยแล้ว');

        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        return redirect()->route('roles.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $role = Role::findOrFail($id);
        $permissions = Permission::all();

        return view('roles.edit', compact('role', 'permissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {

        $role = Role::findOrFail($id);//Get role with the given id
        //Validate name and permission fields
        $validation = Validator::make( $request->all(), [
            'name'=>'required|unique:roles,name,'.$id,
            'permissions' =>'required',
        ], [
                'name.required' => 'จำเป็นต้องระบุชื่อ',
                'name.unique' => 'ชื่อที่ระบุถูกใช้งานแล้ว',
                'permissions.required' => 'จำเป็นต้องกำหนดสิทธิ์การเข้าถึง'
            ]

            );

        if ( $validation->fails() ) {
            // change below as required
            return \Redirect::back()->withInput()->withErrors( $validation->messages() );
        }
        else {
            $input = $request->except(['permissions']);
            $permissions = $request['permissions'];
            $role->fill($input)->save();

            $p_all = Permission::all();//Get all permissions

            foreach ($p_all as $p) {
                $role->revokePermissionTo($p); //Remove all permissions associated with role
            }

            foreach ($permissions as $permission) {
                $p = Permission::where('id', '=', $permission)->firstOrFail(); //Get corresponding form //permission in db
                $role->givePermissionTo($p);  //Assign permission to role
            }

            return redirect()->route('roles.edit',$id)
                ->with('flash_message',
                    'แก้ไขสิทธิ์ '. $role->name.' เรียนร้อยแล้ว');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->delete();

        return redirect()->route('roles.index')
            ->with('flash_message',
                'ลบสิทธิ์เรียบร้อยแล้ว');

    }

    public function destroyMany(Request $request)
    {
        if(sizeof($request->multi_id) >0){
            for ($i = 0 ; $i < sizeof($request->multi_id) ; $i++){
                $role = Role::findOrFail($request->multi_id[$i]);
                $role->delete();
            }

            return redirect()->route('roles.index')
                ->with('flash_message',
                    'ลบสิทธิ์เรียบร้อยแล้ว');

        }
        else{
            return redirect()->route('roles.index')
                ->with('warning',
                    'กรุณาเลือกสิทธิ์อย่างน้อย 1 สิทธิ์');
        }

    }


}

dependencies/resources/views/roles/create.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-orange">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li>
                        <a href="{{route('users.index')}}">จัดการบัญชีผู้ใช้</a>
                    </li>

                    <li class="active">
                        <a href="{{route('roles.index')}}"><span class="title">สิทธิ์การเข้าถึง</span></a>
                    </li>

                    <li>
                        <a href="{{route('generals.index')}}"><span class="title">ข้อมูลทั่วไป</span></a>
                    </li>

                    <li>
                        <a href="{{route('email.index')}}"><span class="title">อีเมลระบบ</span></a>
                    </li>

                    <li>
                        <a href="{{route('statuses.index')}}"><span class="title">สถานะเริ่มต้น</span></a>
                    </li>
                    <li>
                        <a href="{{route('languages.index')}}"><span class="title">ภาษา</span></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-orange">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">หน้าแรก</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">ตั้งค่า</a></li>
                <li class="breadcrumb-item"><a href="{{route('roles.index')}}">สิทธิ์การเข้าถึง</a></li>
                <li class="breadcrumb-item active">เพิ่มสิทธิ์การเข้าถึง</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>เพิ่มสิทธิ์การเข้าถึง

                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="card card-transparent">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-12">
                        @if(Session::has('flash_message'))
                            <div class="alert alert-success" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                {!! Session('flash_message') !!}
                            </div>

                        @endif
                            @if (sizeof($errors) != 0)
                                <div class="alert alert-danger" role="alert">
                                    <button class="close" data-dismiss="alert"></button>
                                    @if($errors->has('name')) {{$errors->first('name')}}<br>@endif
                                    @if($errors->has('permissions[]')) {{$errors->first('permissions[]')}}@endif

                                </div>

                            @endif

                        <p class="small hint-text">* จำเป็นต้องระบุ</p>
                        <form id="form-work" class="form-horizontal" role="form" autocomplete="off" action="{{route('roles.store')}}" method="post" novalidate="novalidate">
                            {{csrf_field()}}
                            <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-3 control-label">ชื่อ *</label>
                                <div class="col-md-9">
                                    <input type="text" class="form-control error" id="name" placeholder="Administrator" name="name"  value="{{old('name')}}" required="" aria-required="true" aria-invalid="true">
                                </div>
                            </div>
                            <div class="form-group row{{ $errors->has('permissions[]') ? ' has-error' : '' }}">

                                    <label class="col-md-3 control-label">กำหนดสิทธิ์การเข้าถึง *</label>
                                    <div class="col-md-9">
                                        @foreach ($permissions as $permission)
                                            {{ Form::checkbox('permissions[]',  $permission->id ) }}
                                            {{ Form::label($permission->name, ucfirst($permission->name)) }}<br>

                                        @endforeach
                                    </div>
                            </div>

                            <div class="row" style="padding-top: 10px">
                                <div class="col-md-3">
                                </div>
                                <div class="col-md-9">
                                    <a href="{{route('roles.index')}}" class="btn btn-hotel btn-primary-hotel">กลับ</a>
                                    <button class="btn btn-hotel btn-sec-hotel" type="submit">เพิ่ม</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>



        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
@endsection

dependencies/resources/views/roles/index.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-orange">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li>
                        <a href="{{route('users.index')}}">จัดการบัญชีผู้ใช้</a>
                    </li>

                    <li class="active">
                        <a href="javascript:;"><span class="title">สิทธิ์การเข้าถึง</span></a>
                    </li>

                    <li>
                        <a href="{{route('generals.index')}}"><span class="title">ข้อมูลทั่วไป</span></a>
                    </li>

                    <li>
                        <a href="{{route('email.index')}}"><span class="title">อีเมลระบบ</span></a>
                    </li>

                    <li>
                        <a href="{{route('statuses.index')}}"><span class="title">สถานะเริ่มต้น</span></a>
                    </li>


                    <li>
                        <a href="{{route('languages.index')}}"><span class="title">ภาษา</span></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-orange">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="/admin/dashboard">หน้าแรก</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">ตั้งค่า</a></li>
                <li class="breadcrumb-item active">สิทธิ์การเข้าถึง</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>สิทธิ์การเข้าถึง

                    <a href="{{route('roles.create')}}" class="btn btn-hotel btn-primary-hotel btn-top-page pull-right"><i class="icon-plus"></i> เพิ่มสิทธิ์การเข้าถึง</a>
                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <!-- START card -->
        <div class="card card-transparent">
            <div class="card-block">
                @if(Session::has('flash_message'))
                    <div class="alert alert-success" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('flash_message') !!}
                    </div>

                @endif
                @if(Session::has('warning'))
                    <div class="alert alert-warning" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('warning') !!}
                    </div>

                @endif
                @if(Session::has('danger'))
                    <div class="alert alert-danger" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('danger') !!}
                    </div>

                @endif
                <div class="table-responsive">
                    <div id="basicTable_wrapper" class="dataTables_wrapper no-footer">
                        <form action="{{route('roles_destroymany')}}" method="post">
                            {{csrf_field()}}
                            <table class="table table-hover dataTable no-footer" id="basicTable" role="grid">
                                <thead>
                                <tr role="row">
                                    <th style="width: 1%" class="sorting_desc" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="No.: activate to sort column ascending" aria-sort="descending">ลำดับ</th>
                                    <th style="width: 83%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="Title: activate to sort column ascending">ชื่อ</th>
                                    <th style="width: 15%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1">จัดการ</th>
                                    <th style="width:1%" class="text-center sorting_disabled" rowspan="1" colspan="1" aria-label="">
                                        <button class="btn btn-link"><i class="icon-trash"></i>
                                        </button>
                                    </th>
                                </tr>

                                </thead>
                                <tbody>
                                @if(sizeof($roles) != 0)
                                    @foreach ($roles as $role)
                                        <tr role="row" class="odd">
                                            <td class="v-align-middle sorting_1">
                                                {{ $role->id }}
                                            </td>
                                            <td class="v-align-middle">
                                                {{ $role->name }}
                                            </td>
                                            <td class="v-align-middle">
                                                <a href="{{ route('roles.edit', $role->id) }}" class="btn btn-hotel btn-edit pull-left" style="margin-right: 3px;"><i class="icon-pencil"></i></a>
                                                <button type="button" class="btn btn-hotel btn-delete pull-left" style="margin-right: 3px;" data-target="#deleteModal{{$role->id}}" data-toggle="modal"><i class="icon-trash"></i></button>
                                                <div class="modal fade fill-in disable-scroll" id="deleteModal{{$role->id}}" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
                                                    <div class="modal-dialog">
                                                        <div class="modal-content">
                                                            <div class="modal-header clearfix text-left">
                                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body text-center m-t-20">
                                                                <h5>คุณต้องการลบสิทธิ์ {{$role->name}} ใช่หรือไม่ ?</h5>
                                                                <button type="button" class="btn btn-hotel btn-primary-hotel" data-dismiss="modal" aria-hidden="true">ยกเลิก</button>&nbsp;
                                                                <a href="{{ route('roles.destroy', $role->id) }}" class="btn btn-hotel btn-delete">ลบ</a>

                                                            </div>
                                                        </div>
                                                        <!-- /.modal-content -->
                                                    </div>
                                                    <!-- /.modal-dialog -->
                                                </div>
                                            </td>
                                            <td class="v-align-middle">
                                                <div class="checkbox text-center">
                                                    <input type="checkbox" value="{{$role->id}}" id="checkbox{{$role->id}}" name="multi_id[]">
                                                    <label for="checkbox{{$role->id}}" class="no-padding no-margin"></label>
                                                </div>
                                            </td>
                                        </tr>

                                    @endforeach
                                    @else
                                    <tr><td></td><td>ไม่พบสิทธิ์การเข้าถึงในตอนนี้.</td><td></td><td></td></tr>


                                @endif





                                </tbody>
                                <tfoot>
                                <tr><td></td><td></td><td style="text-align: right">เลือก:</td><td><button type="button" class="btn btn-xs btn-hotel btn-delete" data-target="#deleteMany" data-toggle="modal"><i class="icon-trash"></i> ลบ</button></td>
                                    <div class="modal fade fill-in disable-scroll" id="deleteMany" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header clearfix text-left">
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="pg-close fs-14"></i>
                                                    </button>
                                                </div>
                                                <div class="modal-body text-center m-t-20">
                                                    <h5>คุณต้องการลบสิทธิ์การเข้าถึงที่เลือกใช่หรือไม่ ?</h5>
                                                    <button type="button" class="btn btn-hotel btn-primary-hotel" data-dismiss="modal" aria-hidden="true">ลบ</button>&nbsp;
                                                    <button class="btn btn-hotel btn-delete" type="submit">ลบ</button>

                                                </div>
                                            </div>
                                            <!-- /.modal-content -->
                                        </div>
                                        <!-- /.modal-dialog -->
                                    </div>
                                </tr>



                                </tfoot>
                            </table>
                        </form>
                    </div>
                </div>
            </div>
            <div style="text-align: center">
                {{$roles->links()}}
            </div>
        </div>
        <!-- END card -->


        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->

@endsection