dependencies/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('maqe', 'PostController@index');

Route::prefix('MRTA-backend/console')->group(function (){
    Auth::routes();


    Route::get('email', function (){
        return view('email');
    });

    //Dashboard
    Route::get('dashboard', 'HomeController@index')->name('dashboard');

    //News
    Route::prefix('news')->group(function (){
        Route::resource('news-categories', 'NewsCategoryController');
        Route::post('news-categories/destroymany', 'NewsCategoryController@destroyMany')->name('news_category_destroymany');
    });
    Route::resource('news', 'NewsController');
    Route::post('news/destroymany', 'NewsController@destroyMany')->name('news_destroymany');
    Route::get('news/category-set', 'NewsController@setCategory')->name('news_typeset');

    //Pages
    Route::resource('pages', 'PagesController');
    Route::post('pages/destroymany', 'PagesController@destroyMany')->name('pages_destroymany');

    //Menus
    Route::resource('menus', 'MenusController');

    //Media
    Route::put('media/uploads', 'MediaController@upload')->name('media_upload');
    Route::resource('media', 'MediaController');

    //Construct
    Route::get('construct/update/status/{id}', 'ConstructController@update_status')->name('construct_update_status');
    Route::resource('stations', 'StationController');
    //Stations
    Route::post('stations/destroymany', 'StationController@destroyMany')->name('stations_destroymany');
    Route::prefix('stations')->group(function (){

        //Folder
        Route::post('folder/{id}', 'StationFolderController@store')->name('add_folder');
        Route::get('folder/{id}', 'StationFolderController@show')->name('show_folder');
        Route::put('folder/{id}', 'StationFolderController@update')->name('update_folder');
        Route::delete('folder/{id}', 'StationFolderController@destroy')->name('delete_folder');

        //Uploads
        Route::put('uploads/{id}', 'StationImageController@upload')->name('uploads_progress');

        //Uploads
        Route::delete('uploads/{id}', 'StaionImageController@destroy')->name('uploads_delete');

        //Percent Update
        Route::resource('percent', 'ConstructPercentController');

    });

    Route::prefix('construct')->group(function (){

        //Folder
        Route::resource('pictures', 'ConstructPictureController');

        //Uploads
        Route::put('uploads/{id}', 'ConstructImageController@upload')->name('uploads_progress');

        //Uploads
        Route::delete('uploads/{id}', 'ConstructImageController@destroy')->name('uploads_delete');

        //Percent Update
        Route::resource('percent', 'ConstructPercentController');

    });

    //Construct
    Route::resource('construct', 'ConstructController');
    Route::post('construct/destroymany', 'ConstructController@destroyMany')->name('construct_destroymany');

    //Settings
    Route::prefix('settings')->group(function (){
        //Users
        Route::resource('users', 'UserController');
        Route::post('users/destroymany', 'UserController@destroyMany')->name('users_destroymany');


        //Roles
        Route::resource('roles', 'RoleController');
        Route::post('roles/destroymany', 'RoleController@destroyMany')->name('roles_destroymany');


        //Generals
        Route::resource('generals', 'GeneralController');

        //Email
        Route::resource('email', 'EmailController');

        //Permission
        Route::resource('permissions', 'PermissionController');
        Route::post('permissions/destroymany', 'PermissionController@destroyMany')->name('permission_destroymany');

        //Default Status
        Route::resource('statuses', 'StatusController');

        //Languages
        Route::resource('languages', 'LanguageController');
        Route::post('languages/destroymany', 'LanguageController@destroyMany')->name('language_destroymany');
        Route::get('languages/makedefault/{id}', 'LanguageController@makeDefault')->name('languages_makedefault');

    });


});

dependencies/resources/views/statuses/edit.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-orange">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li>
                        <a href="{{route('users.index')}}">จัดการบัญชีผู้ใช้</a>
                    </li>

                    <li>
                        <a href="{{route('roles.index')}}"><span class="title">สิทธิ์การเข้าถึง</span></a>
                    </li>

                    <li>
                        <a href="{{route('generals.index')}}"><span class="title">ข้อมูลทั่วไป</span></a>
                    </li>

                    <li>
                        <a href="{{route('email.index')}}"><span class="title">อีเมลระบบ</span></a>
                    </li>

                    <li class="active">
                        <a href="{{route('statuses.index')}}"><span class="title">สถานะเริ่มต้น</span></a>
                    </li>


                    <li>
                        <a href="{{route('languages.index')}}"><span class="title">ภาษา</span></a>
                    </li>

                </ul> </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-orange">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">หน้าแรก</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">ตั้งค่า</a></li>
                <li class="breadcrumb-item"><a href="{{route('languages.index')}}">สถานะเริ่มต้น</a></li>
                <li class="breadcrumb-item active">แก้ไข {{$status->name}}</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>แก้ไข {{strtoupper($status->name)}}

                </h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <div class="card card-transparent">
            <div class="card-block">
                <div class="row">
                    <div class="col-md-12">
                        @if(Session::has('flash_message'))
                            <div class="alert alert-success" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                {!! Session('flash_message') !!}
                            </div>

                        @endif
                        @if ($errors->has('name'))
                            <div class="alert alert-danger" role="alert">
                                <button class="close" data-dismiss="alert"></button>
                                @if($errors->has('name')){{ $errors->first('name') }}<br>@endif
                            </div>

                        @endif
                        <p class="small hint-text">* จำเป็นต้องระบุ</p>
                        {{ Form::model($status, array('route' => array('statuses.update', $status->id), 'method' => 'PUT', 'id' => 'form-work', 'class' => 'form-horizontal', 'role'=>'form', 'autocomplete'=>'off','novalidate'=>'novalidate')) }}{{-- Form model binding to automatically populate our fields with permission data --}}

                        <div class="form-group row{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-3 control-label">ชื่อ *</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control error" id="name" placeholder="เผยแพร่" name="name"  value="{{old('name',$status->name)}}" required="" aria-required="true" aria-invalid="true">
                            </div>
                        </div>


                        <div class="row" style="padding-top: 10px">
                            <div class="col-md-3">
                            </div>
                            <div class="col-md-9">
                                <a href="{{route('statuses.index')}}" class="btn btn-hotel btn-primary-hotel">กลับ</a>
                                <button class="btn btn-hotel btn-sec-hotel" type="submit">บันทึก</button>
                            </div>
                        </div>
                        {{Form::close()}}
                    </div>
                </div>
            </div>
        </div>



        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->
@endsection

dependencies/resources/views/statuses/index.blade.php
@extends('layouts.admin')

@section('mini-menu')
    <div class="bg-orange">
        <div class="container">
            <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="4">
                <a href="#" class="btn-link toggle-sidebar hidden-lg-up pg pg-close" data-toggle="horizontal-menu">
                </a>
                <ul>
                    <li>
                        <a href="{{route('users.index')}}">จัดการบัญชีผู้ใช้</a>
                    </li>

                    <li>
                        <a href="{{route('roles.index')}}"><span class="title">สิทธิ์การเข้าถึง</span></a>
                    </li>

                    <li>
                        <a href="{{route('generals.index')}}"><span class="title">ข้อมูลทั่วไป</span></a>
                    </li>

                    <li>
                        <a href="{{route('email.index')}}"><span class="title">อีเมลระบบ</span></a>
                    </li>

                    <li class="active">
                        <a href="javascript:;"><span class="title">สถานะเริ่มต้น</span></a>
                    </li>

                    <li>
                        <a href="{{route('languages.index')}}"><span class="title">ภาษา</span></a>
                    </li>

                </ul>
            </div>
        </div>
    </div>
@endsection
@section('container')
    <div class="bg-orange">
        <div class="container">
            <ol class="breadcrumb breadcrumb-alt">
                <li class="breadcrumb-item"><a href="{{route('dashboard')}}">หน้าแรก</a></li>
                <li class="breadcrumb-item"><a href="javascript:;">ตั้งค่า</a></li>
                <li class="breadcrumb-item active">สถานะเริ่มต้น</li>
            </ol>
        </div>
    </div>
    <!-- START JUMBOTRON -->
    <div class="jumbotron">
        <div class=" container p-l-0 p-r-0   container-fixed-lg sm-p-l-0 sm-p-r-0">
            <div class="inner heading-padding">
                <!-- START BREADCRUMB -->
                <h1>สถานะเริ่มต้น</h1>

            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->
    <!-- START CONTAINER FLUID -->
    <div class=" container    container-fixed-lg">
        <!-- BEGIN PlACE PAGE CONTENT HERE -->
        <!-- START card -->
        <div class="card card-transparent">
            <div class="card-block">
                @if(Session::has('flash_message'))
                    <div class="alert alert-success" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('flash_message') !!}
                    </div>

                @endif
                @if(Session::has('warning'))
                    <div class="alert alert-warning" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('warning') !!}
                    </div>

                @endif
                @if(Session::has('danger'))
                    <div class="alert alert-danger" role="alert">
                        <button class="close" data-dismiss="alert"></button>
                        {!! Session('danger') !!}
                    </div>

                @endif
                <div class="table-responsive">
                    <div id="basicTable_wrapper" class="dataTables_wrapper no-footer">
                            <table class="table table-hover dataTable no-footer" id="basicTable" role="grid">
                                <thead>
                                <tr role="row">
                                    <th style="width: 1%" class="sorting_desc" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="No.: activate to sort column ascending" aria-sort="descending">ลำดับ</th>
                                    <th style="width: 84%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1" aria-label="Title: activate to sort column ascending">ชื่อ</th>
                                    <th style="width: 15%" class="sorting" tabindex="0" aria-controls="basicTable" rowspan="1" colspan="1">จัดการ</th>

                                </tr>

                                </thead>
                                <tbody>
                                @if(sizeof($statuses) != 0)
                                    @foreach ($statuses as $status)
                                        <tr role="row" class="odd">
                                            <td class="v-align-middle sorting_1">
                                                {{ $status->id }}
                                            </td>
                                            <td class="v-align-middle">
                                                {{ $status->name }}
                                            </td>
                                            <td class="v-align-middle">
                                                <a href="{{ route('statuses.edit', $status->id) }}" class="btn btn-hotel btn-edit pull-left" style="margin-right: 3px;"><i class="icon-pencil"></i></a>
                                                <button type="button" class="btn btn-hotel btn-delete pull-left" style="margin-right: 3px;" data-target="#deleteModal{{$status->id}}" data-toggle="modal" disabled><i class="icon-trash"></i></button>

                                            </td>

                                        </tr>

                                    @endforeach
                                @else
                                    <tr><td></td><td>ไม่พบสถานะเริ่มต้นในตอนนี้.</td><td></td><td></td></tr>
                                @endif
                                </tbody>

                            </table>
                    </div>
                </div>
            </div>

        </div>
        <!-- END card -->


        <!-- END PLACE PAGE CONTENT HERE -->
    </div>
    <!-- END CONTAINER FLUID -->

@endsection